name: "Test Action"
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          # - os: macos-latest
          # - os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: debug files
        run: ls -Rla .

      - name: Run tests
        uses: ./.
        id: test-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-owner: "joluizquierdo"
          artifact-repository: "github-action-rust-template-example"
          name: "Jhon"
          surname: "Doe"

      - name: Show output
        run: |
          echo "Action output: ${{ steps.test-action.outputs.greeting-message }}"
